import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import KeyboardArrowDownIcon from '@mui/icons-material/KeyboardArrowDown';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >


        <div className="bg-black text-white flex  py-4">
        <div className="grow flex justify-center">Summer Stale for All swim ANd Free Express Delivery-OFF 50%  <span className="underline ms-3"> Shop now</span></div>
        { <div className="grow-0 flex justify-start me-20">English <KeyboardArrowDownIcon /></div> }
        </div>
        
        {children}
      </body>
    </html>
  );
}
